#!/usr/bin/env bash
# Install yakuake-save-session: symlinks scripts to ~/.local/bin, generates
# systemd units and the autostart entry.
#
# Safe to run multiple times (idempotent).

set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="$HOME/.local/bin"
AUTOSTART_DIR="$HOME/.config/autostart"
SYSTEMD_USER_DIR="$HOME/.config/systemd/user"

echo "=== yakuake-save-session installer ==="
echo "Project dir: $PROJECT_DIR"
echo ""

# --- Make scripts executable and symlink to ~/.local/bin ---
chmod +x "$PROJECT_DIR/scripts/"*.sh
mkdir -p "$BIN_DIR"

ln -sf "$PROJECT_DIR/scripts/save-session.sh" "$BIN_DIR/yakuake-session-save"
ln -sf "$PROJECT_DIR/scripts/restore-session.sh" "$BIN_DIR/yakuake-session-restore"
ln -sf "$PROJECT_DIR/scripts/yakuake-wrapper.sh" "$BIN_DIR/yakuake-session-wrapper"
rm -f "$BIN_DIR/yakuake-session-tmux"  # left over from the tmux-integrated versions
echo "[ok] Scripts symlinked to $BIN_DIR"

# --- Back up and replace Yakuake autostart ---
mkdir -p "$AUTOSTART_DIR"

ORIGINAL_AUTOSTART="$AUTOSTART_DIR/org.kde.yakuake.desktop"
BACKUP_AUTOSTART="$AUTOSTART_DIR/org.kde.yakuake.desktop.bak"
NEW_AUTOSTART="$AUTOSTART_DIR/yakuake-session.desktop"

if [[ -f "$ORIGINAL_AUTOSTART" ]] && [[ ! -f "$BACKUP_AUTOSTART" ]]; then
    cp "$ORIGINAL_AUTOSTART" "$BACKUP_AUTOSTART"
    echo "[ok] Backed up original autostart to $BACKUP_AUTOSTART"
fi

# Disable the original autostart (KDE reads all .desktop files in the dir)
if [[ -f "$ORIGINAL_AUTOSTART" ]]; then
    if ! grep -q '^Hidden=true' "$ORIGINAL_AUTOSTART"; then
        echo "Hidden=true" >> "$ORIGINAL_AUTOSTART"
        echo "[ok] Disabled original Yakuake autostart (Hidden=true)"
    else
        echo "[ok] Original Yakuake autostart already disabled"
    fi
fi

# Generate autostart entry (no hardcoded paths in the repo)
cat > "$NEW_AUTOSTART" <<EOF
[Desktop Entry]
Categories=Qt;KDE;System;TerminalEmulator;
Comment=Yakuake with session save/restore
Exec=$BIN_DIR/yakuake-session-wrapper
GenericName=Drop-down Terminal
Icon=yakuake
Name=Yakuake (Session Manager)
Terminal=false
Type=Application
X-KDE-StartupNotify=false
X-GNOME-Autostart-enabled=true
EOF
echo "[ok] Generated autostart entry at $NEW_AUTOSTART"

# --- Generate and install systemd units ---
mkdir -p "$SYSTEMD_USER_DIR"

cat > "$SYSTEMD_USER_DIR/yakuake-session-autosave.service" <<EOF
[Unit]
Description=Auto-save Yakuake session state (tab layout)

[Service]
Type=oneshot
ExecStart=$BIN_DIR/yakuake-session-save
EOF

cat > "$SYSTEMD_USER_DIR/yakuake-session-autosave.timer" <<EOF
[Unit]
Description=Periodically save Yakuake session state

[Timer]
OnBootSec=2min
OnUnitActiveSec=5min

[Install]
WantedBy=timers.target
EOF

# Shutdown service: triggers ExecStop on logout, sleep, hibernate, shutdown,
# or reboot — any event that would otherwise lose unsaved Yakuake tab state.
#
# Design notes:
#   - DefaultDependencies=no prevents systemd from auto-adding ordering
#     constraints that create a dependency cycle on NixOS (where graphical-
#     session.target is given After= relationships for its Wants= units).
#     On Ubuntu the same definition was simpler but also less portable.
#   - BindsTo + After on the Yakuake autostart unit handles logout: when
#     Yakuake's autostart stops (because the user session is ending), this
#     service stops too, and ExecStop runs the save before Yakuake actually
#     dies. systemd reverses After= for stops, so we stop before the autostart.
#   - Conflicts + Before on shutdown/reboot/sleep/hibernate targets handles
#     the corresponding events: when the target activates, this service stops
#     first (Before=) and ExecStop runs.
#   - WantedBy=default.target makes it enable-able as a regular user service.
#
# The Yakuake autostart unit name is generated by systemd-xdg-autostart-generator
# from the .desktop file. The hyphen in "yakuake-session" is escaped as \x2d.
YAKUAKE_AUTOSTART_UNIT='app-yakuake\x2dsession@autostart.service'

cat > "$SYSTEMD_USER_DIR/yakuake-session-shutdown.service" <<EOF
[Unit]
Description=Save Yakuake session state on logout, sleep, hibernate, or shutdown
DefaultDependencies=no
BindsTo=$YAKUAKE_AUTOSTART_UNIT
After=$YAKUAKE_AUTOSTART_UNIT
Conflicts=shutdown.target reboot.target sleep.target hibernate.target hybrid-sleep.target
Before=shutdown.target reboot.target sleep.target hibernate.target hybrid-sleep.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/true
ExecStop=$BIN_DIR/yakuake-session-save

[Install]
WantedBy=default.target
EOF

systemctl --user daemon-reload
systemctl --user enable --now yakuake-session-autosave.timer
echo "[ok] Enabled systemd autosave timer"
systemctl --user enable --now yakuake-session-shutdown.service
echo "[ok] Enabled systemd shutdown save service"

# --- Remove the tmux Konsole profile from earlier versions ---
# Tabs are plain shells now. The old profile ran a per-tab tmux launcher that no
# longer exists, so leaving it as DefaultProfile would break every new tab.
KONSOLE_PROFILE="$HOME/.local/share/konsole/Yakuake Tmux.profile"
YAKUAKERC="$HOME/.config/yakuakerc"

if [[ -f "$KONSOLE_PROFILE" ]]; then
    rm -f "$KONSOLE_PROFILE"
    echo "[ok] Removed obsolete Konsole profile"
fi

if [[ -f "$YAKUAKERC" ]] && grep -q '^DefaultProfile=Yakuake Tmux.profile' "$YAKUAKERC"; then
    sed -i '/^DefaultProfile=Yakuake Tmux.profile$/d' "$YAKUAKERC"
    echo "[ok] Reset Yakuake to its default profile"
fi

# --- Initial save of current session ---
echo ""
echo "Running initial session save..."
"$BIN_DIR/yakuake-session-save" || echo "[warn] Initial save failed (is Yakuake running?)"

echo ""
echo "=== Installation complete ==="
echo ""
echo "What happens now:"
echo "  - Your Yakuake tab names, order and working directories have been saved"
echo "  - They are auto-saved every 5 minutes (systemd timer)"
echo "  - They are saved on logout/shutdown (systemd shutdown service,"
echo "    ordered to run while Yakuake is still alive)"
echo "  - On next login, the wrapper starts Yakuake and restores those tabs"
echo "  - Tabs are plain shells. Run tmux in one yourself if you want it;"
echo "    tmux persistence is continuum's job, not this project's."
echo ""
echo "To uninstall:"
echo "  systemctl --user disable --now yakuake-session-autosave.timer"
echo "  systemctl --user disable --now yakuake-session-shutdown.service"
echo "  rm -f $BIN_DIR/yakuake-session-{save,restore,wrapper}"
echo "  rm -f $NEW_AUTOSTART"
echo "  rm -f $SYSTEMD_USER_DIR/yakuake-session-{autosave.service,autosave.timer,shutdown.service}"
echo "  Restore $ORIGINAL_AUTOSTART from .bak"
